import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/app/components/Navbar";
import TopSection from "@/app/components/topSection";
import CarModels from "@/app/components/second_sectionn"
import Thirdsection from "@/app/components/third-section"
import Footer from "./components/footer";
import FirstSection from "./components/first";
import { Montserrat } from "next/font/google";
// import { Montenegrin_Gothic_One } from "next/font/google";
const montenegrin = Montserrat({
  weight: "400",
  subsets: ["latin"],
});

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        
        <Navbar className="fixed top-0 left-0 right-0 z-50"/>
        <FirstSection />
        <TopSection />
        <CarModels />
        <Thirdsection />
        {children}
        <Footer />
        </body>
    </html>
  );
}
